language: node_js
node_js:
- lts/boron
- node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kn6245XKmXT1u+cdPDlqnNOwGCc1BxeRHe2RPkHR0JxeT1swxvr7Q9Ul5Y/CFXVr4zade9eaKYu+oAPxjPPT6L5l8qU361vd3zKQsxcxM0Dk8pWbJgBcRE9eSrEac4I5m61M8N90UFb3Ryy+VIrpnDI6IHeEDmtFRW75MwFW/hx4WM0aQU/ovGDpQN0t/+q8dG9RKdUT9/sptdCR0ehDFFnwgxghgNk7rgNItfP5CIYUfjctbmIk8iYwPytKexHGEqjYu09I8u1CoTlKHAwY366eF8Q5jz7pDiVjutxBPynDdPneX2c5G9AQ5ZkIzr4qURyTSLbGIz6cYrRVEjWuyeugwZuZyNHi5LBquZGYpa4HcgQXXSJJ86StGNUuy+mmosK6zmkfysQFSXt5sDVTdvsgMOvIbRTTIpe7oWv9DpurcSCGVIK1Vt3MN09r6V2pLQTkCCHUnvO9/mZHTbjoz8TVg0rU9Cju6kTDZmcl2oClIPa9Lt9nfICV3ofzQeOnujLKBiWmXizqJutQ6llofmVNaZwoUz3vhJAiIKMSLOWJfl61EAFsELGS4t6iGqlOMcIBBV1c9haSOfj1Mv0aRM9PHe/++PeP7mB0bWC7QsbY9auBlUv86yPOideSQLmAC/uJ/B90IhUTsuTrtNcdaRlkA79TKbSZfjuPCfpF8Jo=
  file:
    - "html-encodings.js"
    - "html-encodings.min.js"
  on:
    tags: true
