language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: et8+9iDEOON0u1E15JXmvODCdEOdSkbTGGZEE/Xjfmi9E8oxOn6v4nlFFN7aus+K0Y+XzNfKQ2M6KRkJuhgzKA6oqxNjjOcjYDTQMk87bTAWGs/nEtdVUe/WtmtBP2FSJ+Br7bXTMgnHwmd0kX9e4ToELCO86H7YTs0r2C7PKymaEBemK+hAy7ASfoMkSRSjUT42jYUDKpngh5wOYZZ0zX9vHie7Hv+sVmOIziIoE5DxM9OIP8WPyPK20zKpqctdp4pC0sUWtW+lr3eMJNdZ1pdCxklO5RLY4zJcUIQUzmgy3GrD6shnBKq/NWkXw+X+c8djz+AnAhglTWDCdjYHOX81RgBXDRxohWqmg+sQqXyIy7tqJoqlIoz52NLxqzFQti1ArMX4httSJ6aOogEwx8UOC3x1EL9TvbZQpT/9hsvlBWdsiDmHxI6LKcJc0LHlCngEDWSZ2PMWt8lUM3Byg7OQ+zGQVbWQPJwqLX5Kwpy9F1FfPM7A4HcwEY0P5kD93BLVMeC2e9nQTfrQ3J5PW9AbDG9K97lzCGeliyCbMZb4Chc4zyiV2KZ5VePt6bRuI+E28NDbBzFWsSm7h4BnbmFkHDokSf73rtIfVCgQfFmNXlz1reozgztsUmbOu6WiyLa141KcyR/tJhrRfbogrELXHPOuJ/QhVXObrtwR0Xc=
  file:
    - 'html-encodings.js'
    - 'html-encodings.min.js'
  on:
    tags: true
